title: Soccertanker Stuff
email: e.smith.py@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  Soccertanker

# Build settings
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-seo-tag

compress_html:
        blanklines: true

color_scheme: "nil"

latex:
        source: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-AMS_CHTML
        config: 'MathJax.Hub.Config({ TeX: { equationNumbers: { autoNumber: "AMS" } } })'
