title: Soccertanker Stuff
email: e.smith.py@gmail.com
baseurl: "/" # the subpath of your site, e.g. /blog
url: "//soccertanker.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  Soccertanker

# Build settings
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-seo-tag

compress_html:
        blanklines: true

color_scheme: ""

latex:
        source: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-AMS_CHTML
        config: 'MathJax.Hub.Config({ TeX: { equationNumbers: { autoNumber: "AMS" } } })'

# text at bottom of page
footer_content: "Contact me at <a href=\"mailto:e.smith.py@gmail.com?subject=Soccertanker Stuff Query\">e.smith.py@gmail.com</a>."

# url of logo that shows at website's title
# logo: "/assets/images/logo_title.gif"

# enable site search
search_enabled: true

# enable support for hyphenated search words:
search_tokenizer_separator: /[\s/]+/

aux_links:
        "Website source code":
                - "//github.com/soccertanker/soccertanker.github.io"

# enable links to headers
heading_anchors: true



